---
kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-config
  namespace: default
data:
  key1: 'Hello, World'
  key2: 'Goodbye, Moon'
---
kind: Pod
apiVersion: v1
metadata:
  name: demo-pod
  namespace: default
spec:
  containers:
    - name: container1
      env:
        - name: GREETING # = 'Hello, World'
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: key1
        - name: FAREWELL # = 'Goodbye, Moon'
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: key2