kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: test-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: docker.io/mantusingh/aspnet-core:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: GREETING # = 'Hello, World'
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: key1
            - name: FAREWELL # = 'Goodbye, Moon'
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: key2
      volumes:
        - name: config-volume
          configMap:
            name: demo-config