apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: aspnet-core-app
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
        spec:
          container:
            # Replace meteatamel with your actual DockerHub
            image: docker.io/mantusingh/knative-app:knativebuild
            env:
              - name: APPLICATION-VERSION
                value: "C# App v1"